remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme

title: [Mr. Brewer's Maths Animations]
description: [Short animations demonstrating Maths skills and concepts.]
show_downloads: [false]
